In [1]:
%cd ../../spell_correction

/Users/tyoyo/lab/spell_correction

In [2]:
from spell_correction.t5_spell_corrector import T5SpellCorrector
import pandas as pd

In [3]:
spell_corrector = T5SpellCorrector(
    model_name="google/mt5-small",
    filter_func=lambda c: c["distance"] <= 1 and c["match_len"] >= 1,
    add_original_token_to_masked_text=False  # つけたい時は自分でつけるので
)

In [ ]:
## 実験内容

In [4]:
masked_text_0 = "桶狭間の戦いで <extra_id_0>の鉄砲が織田信長により初めて戦力として使用された。"
original_token = '国友制'

candidates_0 = spell_corrector.calc_next_token_candidates(masked_text_0, original_token)
pd.DataFrame(candidates_0[:10])

  match_ref  match_len  distance  rank token     logit   index
0         国          1       1.0    16    帝国  1.671213  143559
1         国          1       0.0   520     国 -0.841577    3802
2         国          1       1.0   190    中国  0.056584    3161
3         国          1       1.0   371    王国 -0.496447  178207
4         国          1       1.0   521    各国 -0.842082  153859
5         国          1       1.0   660    国土 -1.099448  197233
6         国          1       1.0   698    英国 -1.170436   41573
7         国          1       1.0   943    全国 -1.513785   12309
8         国          1       1.0  1445    三国 -2.050323  134676
9         国          1       1.0  1632    国産 -2.213619   94188

In [5]:
masked_text_1 = "桶狭間の戦いで <extra_id_0>の鉄砲が織田信長により初めて戦力として使用された。 </s>国友制"
original_token = '国友制'

candidates_1 = spell_corrector.calc_next_token_candidates(masked_text_1, original_token)
pd.DataFrame(candidates_1[:10])

  match_ref  match_len  distance  rank token     logit   index
0         国          1       0.0    26     国  1.421271    3802
1         国          1       1.0    18    帝国  1.645677  143559
2         国          1       1.0    78    中国  0.807722    3161
3         国          1       1.0   188    各国  0.197369  153859
4         国          1       1.0   249    王国 -0.023900  178207
5         国          1       1.0   314    全国 -0.244882   12309
6         国          1       1.0   477    英国 -0.593468   41573
7         国          1       1.0   560    国内 -0.765580   20027
8         国          1       1.0   581    国際 -0.809106   46988
9         国          1       1.0   604    国家 -0.851204    9334

In [6]:
masked_text_0 = "ひきこもりの <extra_id_0>をはじめたきっかけ"
original_token = '更正'

candidates_0 = spell_corrector.calc_next_token_candidates(masked_text_0, original_token)
pd.DataFrame(candidates_0[:30])

   match_ref  match_len  distance   rank token      logit   index
0         更正          2       1.0   1275    矯正  -2.190703  190284
1          更          1       0.0   3005     更  -3.754842    9411
2          更          1       1.0   4856    更新  -4.876542   16449
3         更正          2       1.0   6658    不正  -5.689580  167837
4         更正          2       1.0   6861    修正  -5.764673   88101
5         更正          2       1.0   6987    補正  -5.822224  182192
6         更正          2       1.0  10123    真正  -6.813757   81217
7          更          1       1.0  11560    更に  -7.179368   91676
8         更正          2       1.0  22173    大正  -8.778048  213565
9         更正          2       1.0  23092    適正  -8.870192  176439
10         更          1       1.0  23504    変更  -8.911615   44744
11        更正          2       1.0  32888    公正  -9.677392  158903
12         更          1       1.0  45292    更多 -10.425739   35353

In [7]:
masked_text_1 = "ひきこもりの <extra_id_0>をはじめたきっかけ </s>更正"
original_token = '更正'

candidates_1 = spell_corrector.calc_next_token_candidates(masked_text_1, original_token)
pd.DataFrame(candidates_1[:30])

   match_ref  match_len  distance   rank token     logit   index
0          更          1       0.0   1301     更 -1.958642    9411
1         更正          2       1.0   2177    矯正 -2.764218  190284
2         更正          2       1.0   4909    不正 -4.352059  167837
3         更正          2       1.0   6971    修正 -5.169327   88101
4          更          1       1.0   5322    更新 -4.532378   16449
5         更正          2       1.0   9153    補正 -5.873126  182192
6         更正          2       1.0   9466    真正 -5.951502   81217
7          更          1       1.0  10040    更に -6.098420   91676
8         更正          2       1.0  19255    公正 -7.603002  158903
9         更正          2       1.0  23371    適正 -8.005437  176439
10         更          1       1.0  17848    変更 -7.437726   44744
11         更          1       1.0  18894    更多 -7.558784   35353
12        更正          2       1.0  33738    大正 -8.747050  213565
13        更正          2       1.0  40655    改正 -9.126222  108389
14         更          1       1.0  36331    更加 -8.898301   56424
15         更          1       1.0  40543    更有 -9.120190  184355
16         更          1       1.0  41479    更是 -9.166246  104763

In [10]:
masked_text = "民主党の予備選挙ではヒラリー・クリントンが1位となり、バラク・オバマが僅差の2位 <extra_id_0>"
original_token = 'だた'

candidates = spell_corrector.calc_next_token_candidates(masked_text, original_token)
pd.DataFrame(candidates[:10])

  match_ref  match_len  distance  rank token      logit   index
0        だた          2       1.0    16   だった  -2.245376    9372
1         だ          1       0.0    33     だ  -3.988931    5908
2        だた          2       1.0   232    した  -7.404077    2166
3         だ          1       1.0   242    だと  -7.466586   14396
4         だ          1       1.0   275    だが  -7.746605   40213
5         だ          1       1.0   387    だけ  -8.286261   13386
6        だた          2       1.0   665    いた  -9.303927   10963
7         だ          1       1.0   510    だよ  -8.819601   81198
8         だ          1       1.0   738    だし  -9.506489   42809
9        だた          2       1.0  1264    出た -10.484030  180922

In [11]:
masked_text = "民主党の予備選挙ではヒラリー・クリントンが1位となり、バラク・オバマが僅差の2位 <extra_id_0> </s> だた"
original_token = 'だた'

candidates = spell_corrector.calc_next_token_candidates(masked_text, original_token)
pd.DataFrame(candidates[:10])

  match_ref  match_len  distance  rank token     logit   index
0        だた          2       1.0     6   だった -1.498347    9372
1         だ          1       0.0    19     だ -2.509091    5908
2         だ          1       1.0    89    だが -5.793127   40213
3        だた          2       1.0   230    した -7.170784    2166
4         だ          1       1.0   184    だと -6.810110   14396
5         だ          1       1.0   309    だよ -7.662759   81198
6         だ          1       1.0   333    だけ -7.779253   13386
7        だた          2       1.0   489    いた -8.538112   10963
8         だ          1       1.0   368    だし -7.970039   42809
9        だた          2       1.0   985    出た -9.783148  180922

In [13]:
masked_text = "クラゲには <extra_id_0>を持つが触手はもたない。"  # '' -> 'の'
original_token = '4つ放射管'

candidates = spell_corrector.calc_next_token_candidates(masked_text, original_token)
pd.DataFrame(candidates[:10])

  match_ref  match_len  distance  rank token     logit   index
0         4          1       0.0   358     4 -0.116259     410
1        4つ          2       1.0   652    うつ -0.770533  156435
2        4つ          2       1.0   829    もつ -1.019156  221446
3        4つ          2       1.0   880    ぶつ -1.100002  201210
4        4つ          2       1.0   914    二つ -1.156301  196138
5        4つ          2       1.0  1837    一つ -2.153118   87573
6        4つ          2       1.0  1865    立つ -2.174242  198057
7         4          1       1.0  1460    ▁4 -1.782150     419
8        4つ          2       1.0  2867    つつ -2.885904  116676
9        4つ          2       1.0  3106    持つ -3.032336  148329

In [14]:
masked_text = "クラゲには <extra_id_0>を持つが触手はもたない。 </s>4つ放射管"  # '' -> 'の'
original_token = '4つ放射管'

candidates = spell_corrector.calc_next_token_candidates(masked_text, original_token)
pd.DataFrame(candidates[:10])

  match_ref  match_len  distance  rank token     logit   index
0         4          1       0.0   129     4  1.095028     410
1        4つ          2       1.0   459    うつ -0.038024  156435
2        4つ          2       1.0  1097    もつ -1.008530  221446
3        4つ          2       1.0  1196    ぶつ -1.111096  201210
4        4つ          2       1.0  1316    立つ -1.211438  198057
5        4つ          2       1.0  1578    二つ -1.472143  196138
6         4          1       1.0  1258    ▁4 -1.161815     419
7        4つ          2       1.0  2579    一つ -2.209877   87573
8         4          1       1.0  1671    14 -1.546688    1635
9        4つ          2       1.0  2824    やつ -2.365768  114380

In [16]:
masked_text = "クラゲには4 <extra_id_0>を持つが触手はもたない。"  # '' -> 'の'
original_token = 'つ放射管'

candidates = spell_corrector.calc_next_token_candidates(masked_text, original_token)
pd.DataFrame(candidates[:10])

  match_ref  match_len  distance  rank token     logit   index
0         つ          1       0.0     1     つ  2.461392    7513
1         つ          1       1.0     0    つの  2.758966   35623
2         つ          1       1.0   115    つめ -1.911901  197229
3         つ          1       1.0   174    つ目 -2.398425  233297
4         つ          1       1.0   203    つか -2.665169   75464
5         つ          1       1.0   285    つま -3.056445  178313
6         つ          1       1.0   326    つは -3.259197  220913
7         つ          1       1.0   637    つく -4.321195   61530
8         つ          1       1.0   683    つけ -4.424842   60624
9         つ          1       1.0   722    っつ -4.514354  209950

In [15]:
masked_text = "クラゲには4 <extra_id_0>を持つが触手はもたない。 </s>つ放射管"  # '' -> 'の'
original_token = 'つ放射管'

candidates = spell_corrector.calc_next_token_candidates(masked_text, original_token)
pd.DataFrame(candidates[:10])

  match_ref  match_len  distance  rank token     logit   index
0         つ          1       0.0     1     つ  2.572950    7513
1         つ          1       1.0     0    つの  3.876789   35623
2         つ          1       1.0   169    つは -2.044180  220913
3         つ          1       1.0   235    つか -2.447975   75464
4         つ          1       1.0   245    つ目 -2.490905  233297
5         つ          1       1.0   373    つめ -3.061867  197229
6         つ          1       1.0   499    つと -3.507246  223414
7         つ          1       1.0   640    つま -3.906647  178313
8         つ          1       1.0  1044    つく -4.670190   61530
9         つ          1       1.0  1230    うつ -4.928340  156435

In [17]:
masked_text = "クラゲには4つ <extra_id_0>を持つが触手はもたない。"  # '' -> 'の'
original_token = '放射管'

candidates = spell_corrector.calc_next_token_candidates(masked_text, original_token)
pd.DataFrame(candidates[:10])

  match_ref  match_len  distance   rank token     logit   index
0        放射          2       1.0   2440    反射 -4.946811  154237
1        放射          2       1.0   2527    注射 -5.013861  193502
2         放          1       0.0   2684     放 -5.138742   11215
3         放          1       1.0   2551    解放 -5.033765  112781
4         放          1       1.0   2650    放置 -5.110404  122462
5         放          1       1.0   3101    開放 -5.429188  148405
6         放          1       1.0   3926    手放 -5.905920  224867
7         放          1       1.0   9370    を放 -8.020715  214310
8        放射          2       1.0  12444    照射 -8.765122  191487
9         放          1       1.0   9640    放大 -8.094336  210626

In [18]:
masked_text = "クラゲには4つ <extra_id_0>を持つが触手はもたない。 </s>放射管"  # '' -> 'の'
original_token = '放射管'

candidates = spell_corrector.calc_next_token_candidates(masked_text, original_token)
pd.DataFrame(candidates[:10])

  match_ref  match_len  distance  rank token     logit   index
0        放射          2       1.0   395    注射 -1.441278  193502
1        放射          2       1.0   907    反射 -2.458748  154237
2         放          1       0.0  1102     放 -2.708154   11215
3        放射          2       0.0  1966    放射 -3.573885  166590
4         放          1       1.0  2501    放置 -3.949289  122462
5         放          1       1.0  3505    解放 -4.573989  112781
6        放射          2       1.0  5241    照射 -5.460785  191487
7         放          1       1.0  4211    開放 -4.958221  148405
8         放          1       1.0  6031    を放 -5.773247  214310
9         放          1       1.0  7163    手放 -6.195611  224867